<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.cv</groupId>
        <artifactId>knowledge-parent</artifactId>  <!-- 注意这里必须和父包一致 -->
        <version>1.0.0</version>
        <!-- 由于是独立仓库，relativePath 可以指向本地父包路径或直接不写 -->
        <!-- <relativePath>../knowledge-parent/pom.xml</relativePath> -->
    </parent>

    <groupId>com.cv</groupId>
    <artifactId>dev-lite</artifactId>
    <version>1.0.0</version>

    <packaging>pom</packaging>
    <modules>
        <module>c1-orm-solution</module>
        <module>c2-auth-solution</module>
        <module>c3-async-solution</module>
        <module>c4-network-solution</module>
        <module>c5-file-solution</module>
        <module>c6-cache-solution</module>
        <module>c7-message-solution</module>
        <module>c8-config-ops-solution</module>
        <module>c9-testing-solution</module>
        <module>c10-utils-solution</module>
        <module>c11-jvm-solution</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


</project>